# Done to increase the memory available to Gradle.
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Mod Properties
mod_id = alwaysshield
mod_name = Always Shield
mod_version = 1.2.1
mod_description = Removes the obnoxious block delay of the shield, so it works the moment you press Right-Click. No more delay and confusion!
mod_license = MIT
mod_authors = JustMili

maven_group = net.justmili.alwaysshield
archives_base_name = AlwaysShield

minecraft_version_constraint_fabric = ~26.3-
supported_versions = 26.3-snapshot-1

# Dependencies
mod_menu = 18.0.0-alpha.8