# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=26.2-snapshot-1
short_mcv = 26.2
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=1.2.1-SNAPSHOTS
maven_group=net.justmili
archives_base_name=AlwaysShield